### ISSUE TITLE
remove multi account mode switch  from settings

### ISSUE THREAD

**Issue by AntonPuko** [Brewskey/Brewskey.App#176]

**Comment by jlkalberer** [comment]
Can you add details why?

**Comment by AntonPuko** [comment]
yeah. The feature is not implemented in the current version and probably won't be for a long time ( or its important?). And when it will be implemented the switch is redundant. it will look something like that on menu page.
![111](https://user-images.githubusercontent.com/8849922/37520002-0b7a48be-2924-11e8-95dc-965b64bcf4bc.png)

**Comment by jlkalberer** [comment]
This feature isn't important. I added it a long time ago when there was some bugs in the firmware and this made it easy for me to log people in.
