### ISSUE TITLE
[V2]: Clicking notifications crashes the apps

### ISSUE THREAD

**Issue by jlkalberer** [Brewskey/Brewskey.App#195]
When I click a low keg level notification, it just crashes the app.

Also, make sure that the achievement notifications work as well. When you click on these it should pop up the achievement description.

**Comment by AntonPuko** [comment]
`When I click a low keg level notification, it just crashes the app.` - can you provide more details? I can't reproduce nor on emulator either on a real device. You click on notification from tray? when app is in background or killed? notification comes from `/api/v2/push/test-tap`?  is debug mode on/off when you're seeing that?

**Comment by jlkalberer** [comment]
I am pretty sure I saw it in both scenarios.

I know for sure I saw it when the app was closed/minimized and I clicked it from the Android tray.

**Comment by AntonPuko** [comment]
hm...Idk..will keep finding.

What about new achievement, currently it opens stats screen where there are all badges . I'll to make that it opesns the modal with a particular badge but it's not as easy since the modal doesn't have a route.

**Comment by jlkalberer** [comment]
Not sure how to do the routing but the LoadObject shouldn't really be an issue. I'm fine with a spinner until the achievement loads.
