### ISSUE TITLE
[v2]: Add permissions checks

### ISSUE THREAD

**Issue by jlkalberer** [Brewskey/Brewskey.App#252]
We need to check permissions before allowing people to see `You don't have keg on the tap` or other things that would take them to the setup flows. I think this is also available for flow sensors

We should move this logic to some sort of store -- I made a permissions API call on the stats page for taps that can utilize this as well

**Comment by AntonPuko** [comment]
closed by https://github.com/Brewskey/Brewskey.App/commit/fee8219fff13d45c97a2dfb9ddf27fa161edc2ee
