### ISSUE TITLE
[v2] proper handling 401 errors

### ISSUE THREAD

**Issue by AntonPuko** [Brewskey/Brewskey.App#71]
Since we use LoadObjects, many errors are swallowed now, including 401 which should be handled in some root place.... Is this makes sense to implement somehting like subscribeToError() in DAOApi,and use it as method for catching all critical error?

**Comment by jlkalberer** [comment]
I wouldn't think that the error is necessarily swallowed. It's stored in the load object so the UI should decide what to do with it.

I think using the error in the context of the UI is a better approach than just throwing up a global "Some error happened" toast.

**Comment by AntonPuko** [comment]
but in terms of our app exactly 401 error means that token is expired and we have to relogin user. Define this logic in every ui-error component is overwhelming

**Comment by jlkalberer** [comment]
Ahh... yeah, that should be handle at a lower level. The rest of the errors should be fine though right?

**Comment by AntonPuko** [comment]
Yeah, other errors are ok

**Comment by jlkalberer** [comment]
I think a good start would be to add a subscribe on error like you said.  That can be done as a static on `DAO.js`

BTW - I think Slack is dead today :/

**Comment by jlkalberer** [comment]
You can add a PR for that if you want.

**Comment by AntonPuko** [comment]
yep, slack is dead -(
