### ISSUE TITLE
[V2]: Search location for nearby

### ISSUE THREAD

**Issue by jlkalberer** [Brewskey/Brewskey.App#73]
It would be great if you could either use GPS or use google to search by address to find nearby locations.

I think we would need a search button in the nav-bar that shows a text input when clicked.  I'm hoping there is an existing component or some example that shows how to use the google api.  If you need an API token, I can get you one for this.

**Comment by AntonPuko** [comment]
do you want only text input or also a map where we can select some point?

**Comment by jlkalberer** [comment]
Keep it simple first

**Comment by AntonPuko** [comment]
this can be closed
