### ISSUE TITLE
[v2] add signalr

### ISSUE THREAD

**Issue by AntonPuko** [Brewskey/Brewskey.App#97]

**Comment by jlkalberer** [comment]
I'm on the fence if we want to add this in. It might make more sense to just use background push notifications.

**Comment by AntonPuko** [comment]
I'm not familiar with push notifications yet, but aren't those two separate concepts? how our app will know when push the notification without permanent background connection?

**Comment by jlkalberer** [comment]
Yeah, you can do foreground/background push notifications.

I supported push notifications in another app I built in the past but haven't finished it for Brewskey yet. I copy/pasted the code so it should be a day to make work but I'm not motivated right now.
